apr:
  osx:
    macports:
      packages: [apr]
assimp:
  osx:
    macports:
      packages: [assimp]
atlas:
  osx:
    macports:
      packages: [atlas]
autoconf:
  osx:
    macports:
      packages: [autoconf]
automake:
  osx:
    macports:
      packages: [automake]
bazaar:
  osx:
    macports:
      packages: [bazaar]
bison:
  osx:
    macports:
      packages: [bison]
boost:
  osx:
    macports:
      packages: [boost]
bullet:
  osx:
    macports:
      packages: [bullet]
bzip2:
  osx:
    macports:
      packages: [bzip2]
checkinstall:
  osx:
    macports:
      packages: []
cmake:
  osx:
    macports:
      packages: [cmake]
collada-dom:
  osx:
    macports:
      packages: [collada-dom]
cppunit:
  osx:
    macports:
      packages: [cppunit]
curl:
  osx:
    macports:
      packages: [curl]
doxygen:
  osx:
    macports:
      packages: [doxygen]
eigen:
  osx:
    macports:
      packages: [eigen3]
epydoc:
  osx:
    macports:
      packages: [py27-epydoc]
ffmpeg:
  osx:
    macports:
      packages: [ffmpeg]
flex:
  osx:
    macports:
      packages: [flex]
fltk:
  osx:
    macports:
      packages: [fltk]
freeimage:
  osx:
    macports:
      packages: [freeimage]
freetype:
  osx:
    macports:
      packages: [freetype]
gazebo:
  osx:
    macports:
      packages: []
gfortran:
  osx:
    macports:
      packages: []
git:
  osx:
    macports:
      packages: [git-core]
glut:
  osx:
    macports:
      packages: [freeglut]
graphviz:
  osx:
    macports:
      packages: [graphviz]
gtest:
  osx:
    macports:
      packages: [google-test]
gtk2:
  osx:
    macports:
      packages: [gtk2]
hddtemp:
  osx:
    macports:
      packages: [python27]
hdf5:
  osx:
    macports:
      packages: [hdf5]
jasper:
  osx:
    macports:
      packages: [jasper]
libflann:
  osx:
    macports:
      packages: [flann]
libflann-dev:
  osx:
    macports:
      packages: [flann]
libgsl:
  osx:
    macports:
      packages: [gsl]
libjpeg:
  osx:
    macports:
      packages: [jpeg]
liblapack-dev:
  osx:
    macports:
      packages: []
libmysqlclient-dev:
  osx:
    macports:
      packages: [mysql5]
libogg:
  osx:
    macports:
      packages: [libogg]
libogre-dev:
  osx:
    macports:
      packages: [ogre]
libpcap:
  osx:
    macports:
      packages: [libpcap]
libpcl-all:
  osx:
    macports:
      packages: [libpcl]
libpcl-all-dev:
  osx:
    macports:
      packages: [libpcl]
libpgm:
  osx:
    macports:
      packages: []
libpng12-dev:
  osx:
    macports:
      packages: [libpng]
libpoco-dev:
  osx:
    macports:
      packages: [poco]
libqglviewer-qt4-dev:
  osx:
    macports:
      packages: [libQGLViewer]
libqhull:
  osx:
    macports:
      packages: [qhull]
libqt4:
  osx:
    macports:
      packages: [qt4-mac]
libqt4-dev:
  osx:
    macports:
      packages: [qt4-mac]
libqt4-opengl-dev:
  osx:
    macports:
      packages: [qt4-mac]
libtbb:
  osx:
    macports:
      packages: [tbb]
libtheora:
  osx:
    macports:
      packages: [libtheora]
libtiff-dev:
  osx:
    macports:
      packages: [tiff]
libtiff4-dev:
  osx:
    macports:
      packages: [tiff]
libtool:
  osx:
    macports:
      packages: [libtool]
libusb-1.0-dev:
  osx:
    macports:
      packages: [libusb]
libv4l-dev:
  osx:
    macports:
      packages: []
libvtk:
  osx:
    macports:
      packages: [vtk]
libx11:
  osx:
    macports:
      packages: [xorg-libX11]
libxaw:
  osx:
    macports:
      packages: [xorg-libXaw]
libxext:
  osx:
    macports:
      packages: [xorg-libXext]
libxml2:
  osx:
    macports:
      packages: [libxml2]
libxrandr:
  osx:
    macports:
      packages: [xorg-libXrandr]
libxxf86vm:
  osx:
    macports:
      packages: [xorg-libXxf86vm]
log4cxx:
  osx:
    macports:
      packages: [ros-log4cxx]
mercurial:
  osx:
    macports:
      packages: [mercurial]
mongodb-dev:
  osx:
    macports:
      packages: [mongodb]
netpbm:
  osx:
    macports:
      packages: [netpbm]
nvidia-cg:
  osx:
    macports:
      packages: []
opencv2:
  osx:
    macports:
      packages: [opencv]
opencv2.3:
  osx:
    macports:
      packages: [opencv]
opengl:
  osx:
    macports:
      packages: []
openmpi:
  osx:
    macports:
      packages: [openmpi]
pcre:
  osx:
    macports:
      packages: [pcre]
pkg-config:
  osx:
    macports:
      packages: [pkgconfig]
protobuf-dev:
  osx:
    macports:
      packages: [protobuf-cpp]
python:
  osx:
    macports:
      packages: [python27]
python-argparse:
  osx:
    macports:
      packages: [python27]
python-empy:
  osx:
    macports:
      packages: [py27-empy]
python-gtk2:
  osx:
    macports:
      packages: [py27-pygtk]
python-imaging:
  osx:
    macports:
      packages: [py27-pil]
python-kitchen:
  osx:
    macports:
      packages: []
python-matplotlib:
  osx:
    macports:
      packages: [py27-matplotlib]
python-netifaces:
  osx:
    macports:
      packages: [py27-netifaces]
python-nose:
  osx:
    macports:
      packages: [py27-nose]
python-numpy:
  osx:
    macports:
      packages: [py27-numpy]
python-opengl:
  osx:
    macports:
      packages: [py27-opengl]
python-paramiko:
  osx:
    macports:
      packages: [py27-paramiko]
python-psutil:
  osx:
    macports:
      packages: [py27-psutil]
python-qt-bindings:
  osx:
    macports:
      packages: [py27-pyqt4]
python-qt-bindings-gl:
  osx:
    macports:
      packages: []
python-qt-bindings-qwt5:
  osx:
    macports:
      packages: [qwt52]
python-catkin-pkg:
  osx:
    macports:
      packages: [py27-catkin-pkg]
python-pydot:
  osx:
    macports:
      packages: [py27-pydot]
python-rosdep:
  osx:
    macports:
      packages: [py27-rosdep]
python-rosdistro: 
  osx:
    macports:
      packages: [py27-rosdistro]
python-rosinstall:
  osx:
    macports:
      packages: [py27-rosinstall]
python-rospkg:
  osx:
    macports:
      packages: [py27-rospkg]
python-vcstool:
  osx:
    macports:
      packages: [py27-vcstools]
python-wstool:
  osx:
    macports:
      packages: [py27-wstool]
python-scipy:
  osx:
    macports:
      packages: [py27-scipy]
python-setuptools:
  osx:
    macports:
      packages: [py27-setuptools]
python-sip:
  osx:
    macports:
      packages: [py27-sip]
python-sip4:
  osx:
    macports:
      packages: [py27-sip]
python-sphinx:
  osx:
    macports:
      packages: [py27-sphinx]
python-support:
  osx:
    macports:
      packages: []
python-yaml:
  osx:
    macports:
      packages: [py27-yaml]
qt4-qmake:
  osx:
    macports:
      packages: [qt4-mac]
sbcl:
  osx:
    macports:
      packages: [sbcl]
scons:
  osx:
    macports:
      packages: [scons]
sdl-image:
  osx:
    macports:
      packages: [libsdl]
subversion:
  osx:
    macports:
      packages: [subversion]
suitesparse:
  osx:
    macports:
      packages: [SuiteSparse]
swig-wx:
  osx:
    macports:
      packages: []
tango-icon-theme:
  osx:
    macports:
      packages: [tango-icon-theme]
tar:
  osx:
    macports:
      packages: []
tbb:
  osx:
    macports:
      packages: [tbb]
texlive-fonts-extra:
  osx:
    macports:
      packages: [texlive-fonts-extra]
texlive-fonts-recommended:
  osx:
    macports:
      packages: [texlive-fonts-recommended]
texlive-latex-base:
  osx:
    macports:
      packages: [texlive]
texlive-latex-extra:
  osx:
    macports:
      packages: [texlive-latex-extra]
texlive-latex-recommended:
  osx:
    macports:
      packages: [texlive-latex-recommended]
tinyxml:
  osx:
    macports:
      packages: [tinyxml]
unzip:
  osx:
    macports:
      packages: [unzip]
uuid:
  osx:
    macports:
      packages: [ossp-uuid]
wxpython:
  osx:
    macports:
      packages: [py27-wxpython-3.0]
wxwidgets:
  osx:
    macports:
      packages: [wxWidgets-3.0]
yaml:
  osx:
    macports:
      packages: [libyaml]
yaml-cpp:
  osx:
    macports:
      packages: [yaml-cpp]
zlib:
  osx:
    macports:
      packages: [zlib]
zziplib:
  osx:
    macports:
      packages: [libzzip]
